# Generated by Django 4.2.4 on 2023-10-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('reset_token', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='allotment_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='manager_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('reset_token', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('start_date', models.CharField(default='', max_length=100, null=True)),
                ('due_date', models.CharField(default='', max_length=100, null=True)),
                ('total_hrs', models.CharField(default='', max_length=100, null=True)),
                ('progress', models.CharField(default='', max_length=100, null=True)),
                ('random_color', models.CharField(default='', max_length=100, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('position', models.CharField(default='', max_length=100, null=True)),
                ('profile_image', models.ImageField(null=True, upload_to='image')),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='timesheet_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_time', models.CharField(default='', max_length=100, null=True)),
                ('date', models.DateField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rarapp.project_db')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rarapp.user_db')),
            ],
        ),
        migrations.AddField(
            model_name='project_db',
            name='users',
            field=models.ManyToManyField(to='rarapp.user_db'),
        ),
        migrations.CreateModel(
            name='milestone_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('release_date', models.DateField(default=None, null=True)),
                ('expected_date', models.DateField(default=None, null=True)),
                ('actual_date', models.DateField(default=None, null=True)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rarapp.project_db')),
            ],
        ),
        migrations.CreateModel(
            name='allotment_user_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_time', models.CharField(default='', max_length=100, null=True)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
                ('allotment', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rarapp.allotment_db')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rarapp.user_db')),
            ],
        ),
        migrations.AddField(
            model_name='allotment_db',
            name='project',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rarapp.project_db'),
        ),
    ]
