# Generated by Django 4.2.4 on 2023-10-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment_user_db',
            name='user_alloted',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
